name : Python CI

#Trigger the workflow on any oush to the main branch or pull request

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #step -1 : check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

      #steo - 2 : set up the python environment
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

      # step -3 : Install the dependencies
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      # set 4: Run tests
    - name: Run tests
      run: pytest

